version: '3.3'

services:
  mysql:
    container_name: mysql
    image: percona/percona-server:8.0
    networks:
      - converso-whatsapp-api-net
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Bahia
    volumes:
      - mysql_data:/var/lib/mysql
    expose:
      - 3306

volumes:
  mysql_data:


networks:
  converso-whatsapp-api-net:
    name: converso-whatsapp-api-net
    driver: bridge
